name: DartExample
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: dengkangkang <jaedongkk@163.com>

dependencies:
  intl: ^0.15.8

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
